# A. Libraries

In [3]:
import pandas as pd
import numpy as np
import pickle
import json

# B. Model load

In [15]:
with open('model_randomforest_improve.pkl', 'rb') as file_1:
    model_randomforest_improve = pickle.load(file_1)

with open('model_scaler_n.pkl', 'rb') as file_2:
    model_scaler_n = pickle.load(file_2)

with open('model_scaler_s.pkl', 'rb') as file_3:
    model_scaler_s = pickle.load(file_3)

with open('model_encoder.pkl', 'rb') as file_4:
    model_encoder = pickle.load(file_4)

with open('list_num_col_n.txt', 'r') as file_5:
    list_num_col_n = json.load(file_5)

with open('list_num_col_s.txt', 'r') as file_6:
    list_num_col_s = json.load(file_6)

with open('list_cat_col.txt', 'r') as file_7:
    list_cat_col = json.load(file_7)

# C. Data Inference

In [16]:
data_inf = {'Unnamed: 0': {0: 0, 1: 1, 2: 2, 3: 3, 4: 4},
 'SK_ID_CURR': {0: 100002, 1: 100003, 2: 100004, 3: 100006, 4: 100007},
 'TARGET': {0: 1, 1: 0, 2: 0, 3: 0, 4: 0},
 'NAME_CONTRACT_TYPE': {0: 'Cash loans',
  1: 'Cash loans',
  2: 'Revolving loans',
  3: 'Cash loans',
  4: 'Cash loans'},
 'CODE_GENDER': {0: 'M', 1: 'F', 2: 'M', 3: 'F', 4: 'M'},
 'FLAG_OWN_CAR': {0: 'N', 1: 'N', 2: 'Y', 3: 'N', 4: 'N'},
 'FLAG_OWN_REALTY': {0: 'Y', 1: 'N', 2: 'Y', 3: 'Y', 4: 'Y'},
 'CNT_CHILDREN': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'AMT_INCOME_TOTAL': {0: 202500.0,
  1: 270000.0,
  2: 67500.0,
  3: 135000.0,
  4: 121500.0},
 'AMT_CREDIT': {0: 406597.5,
  1: 1293502.5,
  2: 135000.0,
  3: 312682.5,
  4: 513000.0},
 'AMT_ANNUITY': {0: 24700.5, 1: 35698.5, 2: 6750.0, 3: 29686.5, 4: 21865.5},
 'AMT_GOODS_PRICE': {0: 351000.0,
  1: 1129500.0,
  2: 135000.0,
  3: 297000.0,
  4: 513000.0},
 'NAME_TYPE_SUITE': {0: 'Unaccompanied',
  1: 'Family',
  2: 'Unaccompanied',
  3: 'Unaccompanied',
  4: 'Unaccompanied'},
 'NAME_INCOME_TYPE': {0: 'Working',
  1: 'State servant',
  2: 'Working',
  3: 'Working',
  4: 'Working'},
 'NAME_EDUCATION_TYPE': {0: 'Secondary / secondary special',
  1: 'Higher education',
  2: 'Secondary / secondary special',
  3: 'Secondary / secondary special',
  4: 'Secondary / secondary special'},
 'NAME_FAMILY_STATUS': {0: 'Single / not married',
  1: 'Married',
  2: 'Single / not married',
  3: 'Civil marriage',
  4: 'Single / not married'},
 'NAME_HOUSING_TYPE': {0: 'House / apartment',
  1: 'House / apartment',
  2: 'House / apartment',
  3: 'House / apartment',
  4: 'House / apartment'},
 'REGION_POPULATION_RELATIVE': {0: 0.018801,
  1: 0.0035409999999999,
  2: 0.010032,
  3: 0.008019,
  4: 0.028663},
 'DAYS_BIRTH': {0: -9461, 1: -16765, 2: -19046, 3: -19005, 4: -19932},
 'DAYS_EMPLOYED': {0: -637, 1: -1188, 2: -225, 3: -3039, 4: -3038},
 'DAYS_REGISTRATION': {0: -3648.0,
  1: -1186.0,
  2: -4260.0,
  3: -9833.0,
  4: -4311.0},
 'DAYS_ID_PUBLISH': {0: -2120, 1: -291, 2: -2531, 3: -2437, 4: -3458},
 'OWN_CAR_AGE': {0: 9.0, 1: 9.0, 2: 26.0, 3: 9.0, 4: 9.0},
 'FLAG_MOBIL': {0: 1, 1: 1, 2: 1, 3: 1, 4: 1},
 'FLAG_EMP_PHONE': {0: 1, 1: 1, 2: 1, 3: 1, 4: 1},
 'FLAG_WORK_PHONE': {0: 0, 1: 0, 2: 1, 3: 0, 4: 0},
 'FLAG_CONT_MOBILE': {0: 1, 1: 1, 2: 1, 3: 1, 4: 1},
 'FLAG_PHONE': {0: 1, 1: 1, 2: 1, 3: 0, 4: 0},
 'FLAG_EMAIL': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'OCCUPATION_TYPE': {0: 'Laborers',
  1: 'Core staff',
  2: 'Laborers',
  3: 'Laborers',
  4: 'Core staff'},
 'CNT_FAM_MEMBERS': {0: 1.0, 1: 2.0, 2: 1.0, 3: 2.0, 4: 1.0},
 'REGION_RATING_CLIENT': {0: 2, 1: 1, 2: 2, 3: 2, 4: 2},
 'REGION_RATING_CLIENT_W_CITY': {0: 2, 1: 1, 2: 2, 3: 2, 4: 2},
 'WEEKDAY_APPR_PROCESS_START': {0: 'WEDNESDAY',
  1: 'MONDAY',
  2: 'MONDAY',
  3: 'WEDNESDAY',
  4: 'THURSDAY'},
 'HOUR_APPR_PROCESS_START': {0: 10, 1: 11, 2: 9, 3: 17, 4: 11},
 'REG_REGION_NOT_LIVE_REGION': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'REG_REGION_NOT_WORK_REGION': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'LIVE_REGION_NOT_WORK_REGION': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'REG_CITY_NOT_LIVE_CITY': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'REG_CITY_NOT_WORK_CITY': {0: 0, 1: 0, 2: 0, 3: 0, 4: 1},
 'LIVE_CITY_NOT_WORK_CITY': {0: 0, 1: 0, 2: 0, 3: 0, 4: 1},
 'ORGANIZATION_TYPE': {0: 'Business Entity Type 3',
  1: 'School',
  2: 'Government',
  3: 'Business Entity Type 3',
  4: 'Religion'},
 'EXT_SOURCE_1': {0: 0.0830369673913225,
  1: 0.3112673113812225,
  2: 0.5059979305057544,
  3: 0.5059979305057544,
  4: 0.5059979305057544},
 'EXT_SOURCE_2': {0: 0.2629485927471776,
  1: 0.6222457752555098,
  2: 0.5559120833904428,
  3: 0.6504416904014653,
  4: 0.3227382869704046},
 'EXT_SOURCE_3': {0: 0.1393757800997895,
  1: 0.5352762504724826,
  2: 0.7295666907060153,
  3: 0.5352762504724826,
  4: 0.5352762504724826},
 'APARTMENTS_AVG': {0: 0.0247, 1: 0.0959, 2: 0.0876, 3: 0.0876, 4: 0.0876},
 'BASEMENTAREA_AVG': {0: 0.0369, 1: 0.0529, 2: 0.0763, 3: 0.0763, 4: 0.0763},
 'YEARS_BEGINEXPLUATATION_AVG': {0: 0.9722,
  1: 0.9851,
  2: 0.9816,
  3: 0.9816,
  4: 0.9816},
 'YEARS_BUILD_AVG': {0: 0.6192,
  1: 0.7959999999999999,
  2: 0.7552,
  3: 0.7552,
  4: 0.7552},
 'COMMONAREA_AVG': {0: 0.0143, 1: 0.0605, 2: 0.0211, 3: 0.0211, 4: 0.0211},
 'ELEVATORS_AVG': {0: 0.0, 1: 0.08, 2: 0.0, 3: 0.0, 4: 0.0},
 'ENTRANCES_AVG': {0: 0.069, 1: 0.0345, 2: 0.1379, 3: 0.1379, 4: 0.1379},
 'FLOORSMAX_AVG': {0: 0.0833, 1: 0.2917, 2: 0.1667, 3: 0.1667, 4: 0.1667},
 'FLOORSMIN_AVG': {0: 0.125, 1: 0.3333, 2: 0.2083, 3: 0.2083, 4: 0.2083},
 'LANDAREA_AVG': {0: 0.0369, 1: 0.013, 2: 0.0481, 3: 0.0481, 4: 0.0481},
 'LIVINGAPARTMENTS_AVG': {0: 0.0202,
  1: 0.0773,
  2: 0.0756,
  3: 0.0756,
  4: 0.0756},
 'LIVINGAREA_AVG': {0: 0.019, 1: 0.0549, 2: 0.0745, 3: 0.0745, 4: 0.0745},
 'NONLIVINGAPARTMENTS_AVG': {0: 0.0, 1: 0.0039, 2: 0.0, 3: 0.0, 4: 0.0},
 'NONLIVINGAREA_AVG': {0: 0.0, 1: 0.0098, 2: 0.0036, 3: 0.0036, 4: 0.0036},
 'APARTMENTS_MODE': {0: 0.0252, 1: 0.0924, 2: 0.084, 3: 0.084, 4: 0.084},
 'BASEMENTAREA_MODE': {0: 0.0383, 1: 0.0538, 2: 0.0746, 3: 0.0746, 4: 0.0746},
 'YEARS_BEGINEXPLUATATION_MODE': {0: 0.9722,
  1: 0.9851,
  2: 0.9816,
  3: 0.9816,
  4: 0.9816},
 'YEARS_BUILD_MODE': {0: 0.6341, 1: 0.804, 2: 0.7648, 3: 0.7648, 4: 0.7648},
 'COMMONAREA_MODE': {0: 0.0144, 1: 0.0497, 2: 0.019, 3: 0.019, 4: 0.019},
 'ELEVATORS_MODE': {0: 0.0, 1: 0.0806, 2: 0.0, 3: 0.0, 4: 0.0},
 'ENTRANCES_MODE': {0: 0.069, 1: 0.0345, 2: 0.1379, 3: 0.1379, 4: 0.1379},
 'FLOORSMAX_MODE': {0: 0.0833, 1: 0.2917, 2: 0.1667, 3: 0.1667, 4: 0.1667},
 'FLOORSMIN_MODE': {0: 0.125, 1: 0.3333, 2: 0.2083, 3: 0.2083, 4: 0.2083},
 'LANDAREA_MODE': {0: 0.0377, 1: 0.0128, 2: 0.0458, 3: 0.0458, 4: 0.0458},
 'LIVINGAPARTMENTS_MODE': {0: 0.022,
  1: 0.079,
  2: 0.0771,
  3: 0.0771,
  4: 0.0771},
 'LIVINGAREA_MODE': {0: 0.0198, 1: 0.0554, 2: 0.0731, 3: 0.0731, 4: 0.0731},
 'NONLIVINGAPARTMENTS_MODE': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0},
 'NONLIVINGAREA_MODE': {0: 0.0, 1: 0.0, 2: 0.0011, 3: 0.0011, 4: 0.0011},
 'APARTMENTS_MEDI': {0: 0.025, 1: 0.0968, 2: 0.0864, 3: 0.0864, 4: 0.0864},
 'BASEMENTAREA_MEDI': {0: 0.0369, 1: 0.0529, 2: 0.0758, 3: 0.0758, 4: 0.0758},
 'YEARS_BEGINEXPLUATATION_MEDI': {0: 0.9722,
  1: 0.9851,
  2: 0.9816,
  3: 0.9816,
  4: 0.9816},
 'YEARS_BUILD_MEDI': {0: 0.6243, 1: 0.7987, 2: 0.7585, 3: 0.7585, 4: 0.7585},
 'COMMONAREA_MEDI': {0: 0.0144, 1: 0.0608, 2: 0.0208, 3: 0.0208, 4: 0.0208},
 'ELEVATORS_MEDI': {0: 0.0, 1: 0.08, 2: 0.0, 3: 0.0, 4: 0.0},
 'ENTRANCES_MEDI': {0: 0.069, 1: 0.0345, 2: 0.1379, 3: 0.1379, 4: 0.1379},
 'FLOORSMAX_MEDI': {0: 0.0833, 1: 0.2917, 2: 0.1667, 3: 0.1667, 4: 0.1667},
 'FLOORSMIN_MEDI': {0: 0.125, 1: 0.3333, 2: 0.2083, 3: 0.2083, 4: 0.2083},
 'LANDAREA_MEDI': {0: 0.0375, 1: 0.0132, 2: 0.0487, 3: 0.0487, 4: 0.0487},
 'LIVINGAPARTMENTS_MEDI': {0: 0.0205,
  1: 0.0787,
  2: 0.0761,
  3: 0.0761,
  4: 0.0761},
 'LIVINGAREA_MEDI': {0: 0.0193, 1: 0.0558, 2: 0.0749, 3: 0.0749, 4: 0.0749},
 'NONLIVINGAPARTMENTS_MEDI': {0: 0.0, 1: 0.0039, 2: 0.0, 3: 0.0, 4: 0.0},
 'NONLIVINGAREA_MEDI': {0: 0.0, 1: 0.01, 2: 0.0031, 3: 0.0031, 4: 0.0031},
 'FONDKAPREMONT_MODE': {0: 'reg oper account',
  1: 'reg oper account',
  2: 'unknown',
  3: 'unknown',
  4: 'unknown'},
 'HOUSETYPE_MODE': {0: 'block of flats',
  1: 'block of flats',
  2: 'unknown',
  3: 'unknown',
  4: 'unknown'},
 'TOTALAREA_MODE': {0: 0.0149, 1: 0.0714, 2: 0.0688, 3: 0.0688, 4: 0.0688},
 'WALLSMATERIAL_MODE': {0: 'Stone, brick',
  1: 'Block',
  2: 'unknown',
  3: 'unknown',
  4: 'unknown'},
 'EMERGENCYSTATE_MODE': {0: 'No',
  1: 'No',
  2: 'unknown',
  3: 'unknown',
  4: 'unknown'},
 'OBS_30_CNT_SOCIAL_CIRCLE': {0: 2.0, 1: 1.0, 2: 0.0, 3: 2.0, 4: 0.0},
 'DEF_30_CNT_SOCIAL_CIRCLE': {0: 2.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0},
 'OBS_60_CNT_SOCIAL_CIRCLE': {0: 2.0, 1: 1.0, 2: 0.0, 3: 2.0, 4: 0.0},
 'DEF_60_CNT_SOCIAL_CIRCLE': {0: 2.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0},
 'DAYS_LAST_PHONE_CHANGE': {0: -1134.0,
  1: -828.0,
  2: -815.0,
  3: -617.0,
  4: -1106.0},
 'FLAG_DOCUMENT_2': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_3': {0: 1, 1: 1, 2: 0, 3: 1, 4: 0},
 'FLAG_DOCUMENT_4': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_5': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_6': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_7': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_8': {0: 0, 1: 0, 2: 0, 3: 0, 4: 1},
 'FLAG_DOCUMENT_9': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_10': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_11': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_12': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_13': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_14': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_15': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_16': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_17': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_18': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_19': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_20': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'FLAG_DOCUMENT_21': {0: 0, 1: 0, 2: 0, 3: 0, 4: 0},
 'AMT_REQ_CREDIT_BUREAU_HOUR': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0},
 'AMT_REQ_CREDIT_BUREAU_DAY': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0},
 'AMT_REQ_CREDIT_BUREAU_WEEK': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0},
 'AMT_REQ_CREDIT_BUREAU_MON': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0},
 'AMT_REQ_CREDIT_BUREAU_QRT': {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0},
 'AMT_REQ_CREDIT_BUREAU_YEAR': {0: 1.0, 1: 0.0, 2: 0.0, 3: 1.0, 4: 0.0}}

data_inf = pd.DataFrame(data_inf)

data_inf.info()
data_inf

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Columns: 123 entries, Unnamed: 0 to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(42), object(16)
memory usage: 4.8+ KB


Unnamed: 0  SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0           0      100002       1         Cash loans           M            N   
1           1      100003       0         Cash loans           F            N   
2           2      100004       0    Revolving loans           M            Y   
3           3      100006       0         Cash loans           F            N   
4           4      100007       0         Cash loans           M            N   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  ...  \
0               Y             0          202500.0    406597.5  ...   
1               N             0          270000.0   1293502.5  ...   
2               Y             0           67500.0    135000.0  ...   
3               Y             0          135000.0    312682.5  ...   
4               Y             0          121500.0    513000.0  ...   

   FLAG_DOCUMENT_18  FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0                 0                 0                0                0   
1                 0                 0                0                0   
2                 0                 0                0                0   
3                 0                 0                0                0   
4                 0                 0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        0.0                       0.0   
4                        0.0                       0.0   

  AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                        0.0                        0.0   
1                        0.0                        0.0   
2                        0.0                        0.0   
3                        0.0                        0.0   
4                        0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         1.0  
1                        0.0                         0.0  
2                        0.0                         0.0  
3                        0.0                         1.0  
4                        0.0                         0.0  

[5 rows x 123 columns]

I try to input data dummy, so on the next step i can predict this data dummy

# D. Numeric & Categoric Split

In [17]:
data_inf_num_n = data_inf[list_num_col_n]
data_inf_num_s = data_inf[list_num_col_s]
data_inf_cat = data_inf[list_cat_col]

display(data_inf_num_n)
display(data_inf_num_s)
display(data_inf_cat)

SK_ID_CURR  DAYS_BIRTH  EXT_SOURCE_1  DAYS_ID_PUBLISH
0      100002       -9461      0.083037            -2120
1      100003      -16765      0.311267             -291
2      100004      -19046      0.505998            -2531
3      100006      -19005      0.505998            -2437
4      100007      -19932      0.505998            -3458

AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  DAYS_EMPLOYED  EXT_SOURCE_3  \
0          202500.0    406597.5      24700.5           -637      0.139376   
1          270000.0   1293502.5      35698.5          -1188      0.535276   
2           67500.0    135000.0       6750.0           -225      0.729567   
3          135000.0    312682.5      29686.5          -3039      0.535276   
4          121500.0    513000.0      21865.5          -3038      0.535276   

   EXT_SOURCE_2  DAYS_REGISTRATION  DAYS_LAST_PHONE_CHANGE  
0      0.262949            -3648.0                 -1134.0  
1      0.622246            -1186.0                  -828.0  
2      0.555912            -4260.0                  -815.0  
3      0.650442            -9833.0                  -617.0  
4      0.322738            -4311.0                 -1106.0

OCCUPATION_TYPE
0        Laborers
1      Core staff
2        Laborers
3        Laborers
4      Core staff

I split with numerical & I try to split categorical to. 

# E. Scale & Encode

In [19]:
# Nummeric normal
data_inf_num_n_scaled = model_scaler_n.transform(data_inf_num_n)
# Nummeric skew
data_inf_num_s_scaled = model_scaler_s.transform(data_inf_num_s)

# Categories
data_inf_cat_encoded = model_encoder.transform(data_inf_cat)

display(data_inf_num_n_scaled)
display(data_inf_num_s_scaled)
display(data_inf_cat_encoded)

array([[-1.73384368,  1.50719537, -3.01930839,  0.57821802],
       [-1.73383395, -0.16612459, -1.38363971,  1.78954957],
       [-1.73382422, -0.68869343,  0.01194498,  0.30601612],
       [-1.73380477, -0.67930048,  0.01194498,  0.36827154],
       [-1.73379504, -0.89167283,  0.01194498, -0.3079283 ]])

array([[1.51186991e-03, 9.02865169e-02, 9.00315900e-02, 4.50861923e-02,
        1.55407353e-01, 3.07542268e-01, 8.52140078e-01, 7.35787512e-01],
       [2.08891949e-03, 3.11735955e-01, 1.32923833e-01, 4.36481320e-02,
        5.98522243e-01, 7.27773094e-01, 9.51929313e-01, 8.07082945e-01],
       [3.57770742e-04, 2.24719101e-02, 2.00245700e-02, 4.61614751e-02,
        8.15983432e-01, 6.50189791e-01, 8.27334630e-01, 8.10111836e-01],
       [9.34820326e-04, 6.68370787e-02, 1.09477009e-01, 3.88171889e-02,
        5.98522243e-01, 7.60750789e-01, 6.01451038e-01, 8.56244175e-01],
       [8.19410409e-04, 1.16853933e-01, 7.89750790e-02, 3.88197988e-02,
        5.98522243e-01, 3.77471768e-01, 8.25267510e-01, 7.42311277e-01]])

array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]])

# F. Concate

In [20]:
data_inf_final = np.concatenate([data_inf_num_n_scaled, data_inf_num_s_scaled, data_inf_cat_encoded], axis = 1)
data_inf_final

array([[-1.73384368e+00,  1.50719537e+00, -3.01930839e+00,
         5.78218018e-01,  1.51186991e-03,  9.02865169e-02,
         9.00315900e-02,  4.50861923e-02,  1.55407353e-01,
         3.07542268e-01,  8.52140078e-01,  7.35787512e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.73383395e+00, -1.66124589e-01, -1.38363971e+00,
         1.78954957e+00,  2.08891949e-03,  3.11735955e-01,
         1.32923833e-01,  4.36481320e-02,  5.98522243e-01,
         7.27773094e-01,  9.51929313e-01,  8.07082945e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00

# G. Predict

In [21]:
y_pred_inf = model_randomforest_improve.predict(data_inf_final)

y_pred_inf

array([0, 0, 0, 0, 0], dtype=int64)

In [ ]:
y_pred_inf_proba = model_randomforest_improve.predict_proba(data_inf_final)[:,1]

# H. Concatenate Prediction

In [22]:
data_inf['Prediksi_Gagal_Bayar'] = y_pred_inf
data_inf

Unnamed: 0  SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0           0      100002       1         Cash loans           M            N   
1           1      100003       0         Cash loans           F            N   
2           2      100004       0    Revolving loans           M            Y   
3           3      100006       0         Cash loans           F            N   
4           4      100007       0         Cash loans           M            N   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  ...  \
0               Y             0          202500.0    406597.5  ...   
1               N             0          270000.0   1293502.5  ...   
2               Y             0           67500.0    135000.0  ...   
3               Y             0          135000.0    312682.5  ...   
4               Y             0          121500.0    513000.0  ...   

   FLAG_DOCUMENT_19  FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0                 0                 0                0   
1                 0                 0                0   
2                 0                 0                0   
3                 0                 0                0   
4                 0                 0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        0.0                       0.0   
4                        0.0                       0.0   

  AMT_REQ_CREDIT_BUREAU_WEEK AMT_REQ_CREDIT_BUREAU_MON  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        0.0                       0.0   
4                        0.0                       0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  Prediksi_Gagal_Bayar  
0                        0.0                         1.0                     0  
1                        0.0                         0.0                     0  
2                        0.0                         0.0                     0  
3                        0.0                         1.0                     0  
4                        0.0                         0.0                     0  

[5 rows x 124 columns]

In [ ]:
y_pred_inf_proba['proba'] = y_pred_inf_proba


Ini adalah hasil dari data dummy yang telah dimasukkan. Machine learning yang saya buat menggunakan Support Machine Learning dengan menggunakan model random forest yang telah diimprovisasi dengan menambahkan beberapa parameter terbaik, sehingga dapat dikatakan bahwa model yang saya buat sudah cukup baik untuk melakukan prediksi.